<?php
	$key=$_GET['pag'];
	switch ($key){
		case "desarrollo-web": if($key == 'desarrollo-web') {echo "<title>Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Iquitos, Páginas Web Iquitos, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú</title>\n<meta name=\"keywords\" content=\"Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Perú, Páginas Web Perú, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú\" />\n<meta name=\"description\" content=\"Innditec Agencia de Marketing y Diseño de Paginas Web Profesionales, Tambien brindamos servicios de Posicionamiento Web, alquiler de Hosting, Registro de Dominios, y creamos campañas publicitarias utilizando las redes sociales Facebook y Twitter, desarrollamos aplicaciones para android iOS facebook, juegos y mas\" />\n<meta name=\"author\" content=\"Innditec.com\" />\n";}; break;

		case "soporte-tecnico": if($key == 'soporte-tecnico') {echo "<title>Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Iquitos, Páginas Web Iquitos, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú</title>\n<meta name=\"keywords\" content=\"Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Perú, Páginas Web Perú, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú\" />\n<meta name=\"description\" content=\"Innditec Agencia de Marketing y Diseño de Paginas Web Profesionales, Tambien brindamos servicios de Posicionamiento Web, alquiler de Hosting, Registro de Dominios, y creamos campañas publicitarias utilizando las redes sociales Facebook y Twitter, desarrollamos aplicaciones para android iOS facebook, juegos y mas\" />\n<meta name=\"author\" content=\"Innditec.com\" />\n";}; break;

		case "capacitaciones": if($key == 'capacitaciones') {echo "<title>Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Iquitos, Páginas Web Iquitos, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú</title>\n<meta name=\"keywords\" content=\"Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Perú, Páginas Web Perú, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú\" />\n<meta name=\"description\" content=\"Innditec Agencia de Marketing y Diseño de Paginas Web Profesionales, Tambien brindamos servicios de Posicionamiento Web, alquiler de Hosting, Registro de Dominios, y creamos campañas publicitarias utilizando las redes sociales Facebook y Twitter, desarrollamos aplicaciones para android iOS facebook, juegos y mas\" />\n<meta name=\"author\" content=\"Innditec.com\" />\n";}; break;

		case "contactanos": if($key == 'contactanos') {echo "<title>Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Iquitos, Páginas Web Iquitos, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú</title>\n<meta name=\"keywords\" content=\"Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Perú, Páginas Web Perú, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú\" />\n<meta name=\"description\" content=\"Innditec Agencia de Marketing y Diseño de Paginas Web Profesionales, Tambien brindamos servicios de Posicionamiento Web, alquiler de Hosting, Registro de Dominios, y creamos campañas publicitarias utilizando las redes sociales Facebook y Twitter, desarrollamos aplicaciones para android iOS facebook, juegos y mas\" />\n<meta name=\"author\" content=\"Innditec.com\" />\n";}; break;

		case "conocenos": if($key == 'conocenos') {echo "<title>Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Iquitos, Páginas Web Iquitos, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú</title>\n<meta name=\"keywords\" content=\"Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Perú, Páginas Web Perú, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú\" />\n<meta name=\"description\" content=\"Innditec Agencia de Marketing y Diseño de Paginas Web Profesionales, Tambien brindamos servicios de Posicionamiento Web, alquiler de Hosting, Registro de Dominios, y creamos campañas publicitarias utilizando las redes sociales Facebook y Twitter, desarrollamos aplicaciones para android iOS facebook, juegos y mas\" />\n<meta name=\"author\" content=\"Innditec.com\" />\n";}; break;

		case "portafolio": if($key == 'portafolio') {echo "<title>Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Iquitos, Páginas Web Iquitos, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú</title>\n<meta name=\"keywords\" content=\"Diseño de páginas Web Iquitos - Perú -  Creación de Paginas Web en Iquitos - Empresa de Diseño Web en Iquitos - Diseño Web Perú, Páginas Web Perú, Diseño de Páginas Web en Iquitos, Diseño y Desarrollo de Páginas Web en Iquitos Perú\" />\n<meta name=\"description\" content=\"Innditec Agencia de Marketing y Diseño de Paginas Web Profesionales, Tambien brindamos servicios de Posicionamiento Web, alquiler de Hosting, Registro de Dominios, y creamos campañas publicitarias utilizando las redes sociales Facebook y Twitter, desarrollamos aplicaciones para android iOS facebook, juegos y mas\" />\n<meta name=\"author\" content=\"Innditec.com\" />\n";}; break;

		default : echo (
						 "<title>Innditec Innovando el presente, lo mejor en diseño y desarrollo web apps moviles juegos en Iquitos, creacion de paginas web en Iquitos, desarrollo de paginas web en Iquitos, diseño y desarrollo de juegos y aplicaciones en Iquitos</title>\n<meta name=\"description\" content=\"Diseño de paginas web, desarrollo de paginas web, cracion de paginas web, desarrollo de software, diseño y desarrollo de juegos y aplicaciones en Iquitos\" />\n"
						); break;
		}
?>
